### PR TITLE
Resize style

### PR DESCRIPTION
**Pull request by santiagogil**
Hi.
This branch adds support for the resizeStyle option.
I find it usefull for a responsive images plugin that I'm working on.

### CODE REVIEW

**Comment by tomterl** [comment]
Thanks for this contribution, it will come in handy for me and others as well.

I'll push this version to npm tomorrow morning (MET).

**Comment by santiagogil** [comment]
Thanks to you for this great plugin.

**Comment by tomterl** [comment]
Just pushed 0.2.0 to npmjs .

**Comment by santiagogil** [comment]
Great. Thanks.

**Pull request merged**
