### PR TITLE
add stub option

### PR DESCRIPTION
**Pull request by doodzik**

### CODE REVIEW

**Comment by tomterl** [comment]
Thanks, a few remarks
- Please don't mix style changes and functional changes in a single commit (and I won't take the stylistic changes, no offence meant)
- I don't really like the name 'stub' -- I'm not a native English speaker, but I don't associate it directly with 'avoid action/just pretend to do something' -- maybe name it 'rename_only', to make abundantly clear what it does?
- How is your workflow organized, how do you avoid accidental upload of unconverted images? Is there a metalsmith idiom we could use to facilitate the distinction between development/publishing?

**Comment by doodzik** [comment]
No offense taken. Makes sense. The one thing is a refactoring and the other is an addition in functionality.
Sure. It was just a placeholder name.
What do you mean by your last bulletin?

I would suggest using it like this to ensure it is only used in development:

```rename_only: !ENV.PRODUCTION```

**Comment by tomterl** [comment]
Cool - thanks; I think a paragraph in the readme suggesting `rename_only: !ENV.PRODUCTION` and how to set that up would address my concerns w/r point 3 (usability), but thats not that important for now

**Comment by tomterl** [comment]
Nota Bene: I release v0.3.4 later, when I'm at my private machine...

**Pull request merged**
